Support parsing decimal values using `,` as decimal divider
mjj4791/python-buienradar pull request #13
Opened 2021-11-21 18:46 UTC by corneyl

Apparently Buienradar can now send precipitation forecast values in a decimal notation, this was e.g. the precipitation forecast for The Hague tonight:
```
92,2678801510292|19:20
077|19:25
077|19:30
86,6329598612474|19:35
110,3245659250632|19:40
105,8988795837422|19:45
077|19:50
000|19:55
000|20:00
000|20:05
000|20:10
000|20:15
000|20:20
000|20:25
000|20:30
000|20:35
000|20:40
000|20:45
000|20:50
000|20:55
92,2678801510292|21:00
92,2678801510292|21:05
86,6329598612474|21:10
000|21:15
```

This PR adds support for parsing these decimal values.

2021-11-26 13:52 UTC, AdriaanDeVos commented
I can confirm that this PR resolves the issue. Also a nice test is added :+1:

2021-11-27 15:31 UTC, mjj4791 requested changes
see code comments; please also fix this issue when using xml data as source

2021-11-27 15:31 UTC, mjj4791 commented on tests/test_parse_json.py
> +def test_precip_decimal_values():
please also add this testcase into test_parse_xml.py

2021-11-27 15:43 UTC, corneyl commented
@mjj4791 thanks for the review, I've added the fix and a test for the xml version as well.

2021-11-27 16:01 UTC, mjj4791 approved these changes

2021-11-27 16:02 UTC, merged

2021-11-27 16:03 UTC, mjj4791 commented
will package this later today.... https://pypi.org/project/buienradar/

2021-11-27 16:11 UTC, corneyl commented
Thanks a lot @mjj4791!

2021-11-27 23:38 UTC, mjj4791 commented
@corneyl ; code has been release in v1.0.5: https://pypi.org/project/buienradar/1.0.5/

2021-12-12 12:06 UTC, yfands commented
Hey Guys,

Using the latest version 1.0.5

But I have still issues with the fact that Buienradar is not refreshing, as you can see in the image. On the bottom right the actual date and time, sunday the 12th of december. On the left the last time Buienradar was refreshed. on the 9th. If I reset Home assistant also the data is refreshed. I have no errors/warnings in my logfile. How can I be of service and debug the lot to know what is going on.


![Buienradar integration not refreshing](https://user-images.githubusercontent.com/3709952/145711456-c5591827-be24-4973-946e-b2fd2e158feb.jpg)


Regards Frank

2021-12-12 15:53 UTC, mjj4791 commented
Frank

You can enable more logging for the buienradar component by updating your Home assistant configuration.yaml.
in the logs section, you can enable 3 logging configs. the first one will enable logging for the buienradar component in HA; the latter 2 enable logging from within the buienradar library.
(Please note that the 1.0.5 update is part of the 2021.12 update, which became available only yesterday..., you might still be using 1.0.4 library)

Let me know if you see anything suspicious in buienradar logging...

```
logger:
  default: error
  logs:
    homeassistant.components.buienradar: debug
    buienradar.buienradar: debug
    buienradar.buienradar_json: debug
```

2021-12-12 16:23 UTC, IceEyz commented
I had the same issue yesterday, on 1.0.5. Haven't had the chance to do debug logging yet, will try to enable later today.